app = "simulation-api"
primary_region = "fra"

[env]
  APP_ENV = "production"
  APP_URL = "https://simulation-api.fly.dev"
  LOG_CHANNEL = "stderr"
  SESSION_DRIVER = "cookie"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
