name: Fly Deploy

on:
  push:
    branches:
      - main # <--- IMPORTANT: Change this to 'master' if your default branch is 'master'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -a simulation-lingering-tree-3252 # <--- IMPORTANT: Use the latest app name created by flyctl, which is likely 'simulation-lingering-tree-3252'
